# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ITC_control.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ITCcontrol(object):
    def setupUi(self, ITCcontrol):
        ITCcontrol.setObjectName("ITCcontrol")
        ITCcontrol.resize(566, 357)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ITCcontrol.sizePolicy().hasHeightForWidth())
        ITCcontrol.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(ITCcontrol)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 511, 311))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridSetPoints = QtWidgets.QGridLayout()
        self.gridSetPoints.setSpacing(6)
        self.gridSetPoints.setObjectName("gridSetPoints")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridSetPoints.addWidget(self.label_3, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridSetPoints.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridSetPoints.addWidget(self.label_4, 7, 0, 1, 1)
        self.spinsetProportionalID = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinsetProportionalID.setObjectName("spinsetProportionalID")
        self.gridSetPoints.addWidget(self.spinsetProportionalID, 5, 1, 1, 1)
        self.combosetHeatersens = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.combosetHeatersens.setObjectName("combosetHeatersens")
        self.combosetHeatersens.addItem("")
        self.combosetHeatersens.addItem("")
        self.combosetHeatersens.addItem("")
        self.gridSetPoints.addWidget(self.combosetHeatersens, 2, 1, 1, 1)
        self.spinsetPIDerivative = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinsetPIDerivative.setObjectName("spinsetPIDerivative")
        self.gridSetPoints.addWidget(self.spinsetPIDerivative, 7, 1, 1, 1)
        self.spinsetPIntegrationD = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinsetPIntegrationD.setObjectName("spinsetPIntegrationD")
        self.gridSetPoints.addWidget(self.spinsetPIntegrationD, 6, 1, 1, 1)
        self.combosetAutocontrol = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.combosetAutocontrol.setObjectName("combosetAutocontrol")
        self.combosetAutocontrol.addItem("")
        self.combosetAutocontrol.addItem("")
        self.combosetAutocontrol.addItem("")
        self.combosetAutocontrol.addItem("")
        self.gridSetPoints.addWidget(self.combosetAutocontrol, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridSetPoints.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridSetPoints.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridSetPoints.addWidget(self.label_2, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lcdTemp_set = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdTemp_set.sizePolicy().hasHeightForWidth())
        self.lcdTemp_set.setSizePolicy(sizePolicy)
        self.lcdTemp_set.setObjectName("lcdTemp_set")
        self.horizontalLayout_3.addWidget(self.lcdTemp_set)
        self.spinsetTemp = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.spinsetTemp.setDecimals(2)
        self.spinsetTemp.setMaximum(400.0)
        self.spinsetTemp.setObjectName("spinsetTemp")
        self.horizontalLayout_3.addWidget(self.spinsetTemp)
        self.gridSetPoints.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.spinsetHeaterPercent = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.spinsetHeaterPercent.setObjectName("spinsetHeaterPercent")
        self.gridSetPoints.addWidget(self.spinsetHeaterPercent, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridSetPoints.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridSetPoints.addWidget(self.label_17, 1, 0, 1, 1)
        self.spinsetGasOutput = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.spinsetGasOutput.setObjectName("spinsetGasOutput")
        self.gridSetPoints.addWidget(self.spinsetGasOutput, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridSetPoints)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.gridReadings = QtWidgets.QGridLayout()
        self.gridReadings.setHorizontalSpacing(6)
        self.gridReadings.setObjectName("gridReadings")
        self.lcdPIntegrationD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdPIntegrationD.setObjectName("lcdPIntegrationD")
        self.gridReadings.addWidget(self.lcdPIntegrationD, 9, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridReadings.addWidget(self.label_16, 10, 0, 1, 1)
        self.lcdPIDerivative = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdPIDerivative.setObjectName("lcdPIDerivative")
        self.gridReadings.addWidget(self.lcdPIDerivative, 10, 1, 1, 1)
        self.lcdProportionalID = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdProportionalID.setObjectName("lcdProportionalID")
        self.gridReadings.addWidget(self.lcdProportionalID, 8, 1, 1, 1)
        self.lcdHeaterVoltage = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdHeaterVoltage.setObjectName("lcdHeaterVoltage")
        self.gridReadings.addWidget(self.lcdHeaterVoltage, 7, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridReadings.addWidget(self.label_14, 8, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridReadings.addWidget(self.label_15, 9, 0, 1, 1)
        self.lcdTemp_err = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdTemp_err.setObjectName("lcdTemp_err")
        self.gridReadings.addWidget(self.lcdTemp_err, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridReadings.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridReadings.addWidget(self.label_13, 7, 0, 1, 1)
        self.lcdTemp_sens1 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdTemp_sens1.setObjectName("lcdTemp_sens1")
        self.gridReadings.addWidget(self.lcdTemp_sens1, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridReadings.addWidget(self.label_12, 6, 0, 1, 1)
        self.progressHeaterPercent = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressHeaterPercent.setProperty("value", 24)
        self.progressHeaterPercent.setObjectName("progressHeaterPercent")
        self.gridReadings.addWidget(self.progressHeaterPercent, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridReadings.addWidget(self.label_11, 4, 0, 1, 1)
        self.lcdTemp_sens2 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdTemp_sens2.setObjectName("lcdTemp_sens2")
        self.gridReadings.addWidget(self.lcdTemp_sens2, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridReadings.addWidget(self.label_10, 3, 0, 1, 1)
        self.lcdTemp_sens3 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdTemp_sens3.setObjectName("lcdTemp_sens3")
        self.gridReadings.addWidget(self.lcdTemp_sens3, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridReadings.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_NeedleValve = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_NeedleValve.setObjectName("label_NeedleValve")
        self.gridReadings.addWidget(self.label_NeedleValve, 5, 0, 1, 1)
        self.progressNeedleValve = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressNeedleValve.setEnabled(True)
        self.progressNeedleValve.setProperty("value", 0)
        self.progressNeedleValve.setObjectName("progressNeedleValve")
        self.gridReadings.addWidget(self.progressNeedleValve, 5, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridReadings)
        # ITCcontrol.setCentralWidget(self.centralwidget)

        self.retranslateUi(ITCcontrol)
        QtCore.QMetaObject.connectSlotsByName(ITCcontrol)

    def retranslateUi(self, ITCcontrol):
        _translate = QtCore.QCoreApplication.translate
        ITCcontrol.setWindowTitle(_translate("ITCcontrol", "ITC Control"))
        self.label_3.setText(_translate("ITCcontrol", "Integration"))
        self.label.setText(_translate("ITCcontrol", "Set Temp"))
        self.label_4.setText(_translate("ITCcontrol", "Derivative"))
        self.combosetHeatersens.setItemText(0, _translate("ITCcontrol", "Sensor 1"))
        self.combosetHeatersens.setItemText(1, _translate("ITCcontrol", "Sensor 2"))
        self.combosetHeatersens.setItemText(2, _translate("ITCcontrol", "Sensor 3"))
        self.combosetAutocontrol.setItemText(0, _translate("ITCcontrol", "heater man, gas man"))
        self.combosetAutocontrol.setItemText(1, _translate("ITCcontrol", "heater auto, gas man"))
        self.combosetAutocontrol.setItemText(2, _translate("ITCcontrol", "heater man, gas auto"))
        self.combosetAutocontrol.setItemText(3, _translate("ITCcontrol", "heater auto, gas auto"))
        self.label_5.setText(_translate("ITCcontrol", "Heater Output"))
        self.label_6.setText(_translate("ITCcontrol", "Heater Sensor"))
        self.label_2.setText(_translate("ITCcontrol", "Proportional"))
        self.label_7.setText(_translate("ITCcontrol", "Autocontrol"))
        self.label_17.setText(_translate("ITCcontrol", "Gas Output"))
        self.label_16.setText(_translate("ITCcontrol", "Derivative action time"))
        self.label_14.setText(_translate("ITCcontrol", "Proportional band"))
        self.label_15.setText(_translate("ITCcontrol", "Integration action time"))
        self.label_9.setText(_translate("ITCcontrol", "Temperature 2"))
        self.label_13.setText(_translate("ITCcontrol", "Heater Output [V]"))
        self.label_12.setText(_translate("ITCcontrol", "Heater Output [%]"))
        self.label_11.setText(_translate("ITCcontrol", "Temperature error"))
        self.label_10.setText(_translate("ITCcontrol", "Temperature 3"))
        self.label_8.setText(_translate("ITCcontrol", "Temperature 1"))
        self.label_NeedleValve.setText(_translate("ITCcontrol", "Gas Output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ITCcontrol = QtWidgets.QMainWindow()
    ui = Ui_ITCcontrol()
    ui.setupUi(ITCcontrol)
    ITCcontrol.show()
    sys.exit(app.exec_())

