# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ITC_control.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ITCcontrol(object):
    def setupUi(self, ITCcontrol):
        ITCcontrol.setObjectName("ITCcontrol")
        ITCcontrol.resize(529, 398)
        self.centralwidget = QtWidgets.QWidget(ITCcontrol)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 491, 331))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridSetPoints = QtWidgets.QGridLayout()
        self.gridSetPoints.setSpacing(6)
        self.gridSetPoints.setObjectName("gridSetPoints")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.gridSetPoints.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridSetPoints.addWidget(self.label_6, 1, 0, 1, 1)
        self.combosetHeatersens = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.combosetHeatersens.setObjectName("combosetHeatersens")
        self.combosetHeatersens.addItem("")
        self.combosetHeatersens.addItem("")
        self.combosetHeatersens.addItem("")
        self.gridSetPoints.addWidget(self.combosetHeatersens, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridSetPoints.addWidget(self.label_5, 2, 0, 1, 1)
        self.spinsetHeaterPercent = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinsetHeaterPercent.setObjectName("spinsetHeaterPercent")
        self.gridSetPoints.addWidget(self.spinsetHeaterPercent, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridSetPoints.addWidget(self.label_7, 3, 0, 1, 1)
        self.combosetsetAutocontrol = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.combosetsetAutocontrol.setObjectName("combosetsetAutocontrol")
        self.combosetsetAutocontrol.addItem("")
        self.combosetsetAutocontrol.addItem("")
        self.combosetsetAutocontrol.addItem("")
        self.combosetsetAutocontrol.addItem("")
        self.gridSetPoints.addWidget(self.combosetsetAutocontrol, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridSetPoints.addWidget(self.label_2, 4, 0, 1, 1)
        self.spinsetProportioinalID = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinsetProportioinalID.setObjectName("spinsetProportioinalID")
        self.gridSetPoints.addWidget(self.spinsetProportioinalID, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridSetPoints.addWidget(self.label_3, 5, 0, 1, 1)
        self.spinsetPIntegrationD = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinsetPIntegrationD.setObjectName("spinsetPIntegrationD")
        self.gridSetPoints.addWidget(self.spinsetPIntegrationD, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridSetPoints.addWidget(self.label_4, 6, 0, 1, 1)
        self.spinsetPIDerivative = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinsetPIDerivative.setObjectName("spinsetPIDerivative")
        self.gridSetPoints.addWidget(self.spinsetPIDerivative, 6, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lcdTemp_set = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdTemp_set.setObjectName("lcdTemp_set")
        self.horizontalLayout_3.addWidget(self.lcdTemp_set)
        self.spin_setTemp = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spin_setTemp.setObjectName("spin_setTemp")
        self.horizontalLayout_3.addWidget(self.spin_setTemp)
        self.gridSetPoints.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridSetPoints)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.Needle = QtWidgets.QVBoxLayout()
        self.Needle.setObjectName("Needle")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_NeedleValve = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_NeedleValve.setObjectName("label_NeedleValve")
        self.horizontalLayout.addWidget(self.label_NeedleValve)
        self.Force_Needle_enable = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.Force_Needle_enable.setEnabled(False)
        self.Force_Needle_enable.setCheckable(True)
        self.Force_Needle_enable.setChecked(True)
        self.Force_Needle_enable.setObjectName("Force_Needle_enable")
        self.horizontalLayout.addWidget(self.Force_Needle_enable)
        self.Needle.addLayout(self.horizontalLayout)
        self.progressNeedleValve = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressNeedleValve.setEnabled(True)
        self.progressNeedleValve.setProperty("value", 0)
        self.progressNeedleValve.setObjectName("progressNeedleValve")
        self.Needle.addWidget(self.progressNeedleValve)
        self.Needle_slider = QtWidgets.QHBoxLayout()
        self.Needle_slider.setObjectName("Needle_slider")
        self.Slider_Needle = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.Slider_Needle.setEnabled(True)
        self.Slider_Needle.setMaximum(100)
        self.Slider_Needle.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Needle.setObjectName("Slider_Needle")
        self.Needle_slider.addWidget(self.Slider_Needle)
        spacerItem = QtWidgets.QSpacerItem(31, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.Needle_slider.addItem(spacerItem)
        self.Needle.addLayout(self.Needle_slider)
        self.Enable_NeedleValve = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Enable_NeedleValve.setObjectName("Enable_NeedleValve")
        self.Needle.addWidget(self.Enable_NeedleValve)
        self.verticalLayout.addLayout(self.Needle)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.gridReadings = QtWidgets.QGridLayout()
        self.gridReadings.setHorizontalSpacing(6)
        self.gridReadings.setObjectName("gridReadings")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridReadings.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridReadings.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridReadings.addWidget(self.label_13, 6, 0, 1, 1)
        self.lcdTemp_sens1 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdTemp_sens1.setObjectName("lcdTemp_sens1")
        self.gridReadings.addWidget(self.lcdTemp_sens1, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridReadings.addWidget(self.label_12, 5, 0, 1, 1)
        self.progressHeaterPercent = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressHeaterPercent.setProperty("value", 24)
        self.progressHeaterPercent.setObjectName("progressHeaterPercent")
        self.gridReadings.addWidget(self.progressHeaterPercent, 5, 1, 1, 1)
        self.lcdTemp_sens2 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdTemp_sens2.setObjectName("lcdTemp_sens2")
        self.gridReadings.addWidget(self.lcdTemp_sens2, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridReadings.addWidget(self.label_10, 3, 0, 1, 1)
        self.lcdTemp_sens3 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdTemp_sens3.setObjectName("lcdTemp_sens3")
        self.gridReadings.addWidget(self.lcdTemp_sens3, 3, 1, 1, 1)
        self.lcdTemp_err = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdTemp_err.setObjectName("lcdTemp_err")
        self.gridReadings.addWidget(self.lcdTemp_err, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridReadings.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridReadings.addWidget(self.label_14, 7, 0, 1, 1)
        self.lcdHeaterVoltage = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdHeaterVoltage.setObjectName("lcdHeaterVoltage")
        self.gridReadings.addWidget(self.lcdHeaterVoltage, 6, 1, 1, 1)
        self.lcdProportionalID = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdProportionalID.setObjectName("lcdProportionalID")
        self.gridReadings.addWidget(self.lcdProportionalID, 7, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridReadings.addWidget(self.label_15, 8, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridReadings.addWidget(self.label_16, 9, 0, 1, 1)
        self.lcdPIDerivative = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdPIDerivative.setObjectName("lcdPIDerivative")
        self.gridReadings.addWidget(self.lcdPIDerivative, 9, 1, 1, 1)
        self.lcdPIntegrationD = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdPIntegrationD.setObjectName("lcdPIntegrationD")
        self.gridReadings.addWidget(self.lcdPIntegrationD, 8, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridReadings)
        # ITCcontrol.setCentralWidget(self.centralwidget)
        # self.statusbar = QtWidgets.QStatusBar(ITCcontrol)
        # self.statusbar.setObjectName("statusbar")
        # ITCcontrol.setStatusBar(self.statusbar)

        self.retranslateUi(ITCcontrol)
        QtCore.QMetaObject.connectSlotsByName(ITCcontrol)

    def retranslateUi(self, ITCcontrol):
        _translate = QtCore.QCoreApplication.translate
        ITCcontrol.setWindowTitle(_translate("ITCcontrol", "MainWindow"))
        self.label.setText(_translate("ITCcontrol", "Set Temp"))
        self.label_6.setText(_translate("ITCcontrol", "Heater Sensor"))
        self.combosetHeatersens.setItemText(0, _translate("ITCcontrol", "Sensor 1"))
        self.combosetHeatersens.setItemText(1, _translate("ITCcontrol", "Sensor 2"))
        self.combosetHeatersens.setItemText(2, _translate("ITCcontrol", "Sensor 3"))
        self.label_5.setText(_translate("ITCcontrol", "Heater Output"))
        self.label_7.setText(_translate("ITCcontrol", "Autocontrol"))
        self.combosetsetAutocontrol.setItemText(0, _translate("ITCcontrol", "heater man, gas man"))
        self.combosetsetAutocontrol.setItemText(1, _translate("ITCcontrol", "heater auto, gas man"))
        self.combosetsetAutocontrol.setItemText(2, _translate("ITCcontrol", "heater man, gas auto"))
        self.combosetsetAutocontrol.setItemText(3, _translate("ITCcontrol", "heater auto, gas auto"))
        self.label_2.setText(_translate("ITCcontrol", "Prop"))
        self.label_3.setText(_translate("ITCcontrol", "Int"))
        self.label_4.setText(_translate("ITCcontrol", "Derivative"))
        self.label_NeedleValve.setText(_translate("ITCcontrol", "Gas Output"))
        self.Force_Needle_enable.setText(_translate("ITCcontrol", "Needle on manual"))
        self.Enable_NeedleValve.setText(_translate("ITCcontrol", "Force Needle Manual"))
        self.label_8.setText(_translate("ITCcontrol", "Temperature 1"))
        self.label_11.setText(_translate("ITCcontrol", "Temperature error"))
        self.label_13.setText(_translate("ITCcontrol", "Heater Output [V]"))
        self.label_12.setText(_translate("ITCcontrol", "Heater Output [%]"))
        self.label_10.setText(_translate("ITCcontrol", "Temperature 3"))
        self.label_9.setText(_translate("ITCcontrol", "Temperature 2"))
        self.label_14.setText(_translate("ITCcontrol", "Proportional band"))
        self.label_15.setText(_translate("ITCcontrol", "Integration action time"))
        self.label_16.setText(_translate("ITCcontrol", "Derivative action time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ITCcontrol = QtWidgets.QMainWindow()
    ui = Ui_ITCcontrol()
    ui.setupUi(ITCcontrol)
    ITCcontrol.show()
    sys.exit(app.exec_())

