# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cryostat_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_Cryostat_Main(object):
    def setupUi(self, Cryostat_Main):
        Cryostat_Main.setObjectName("Cryostat_Main")
        Cryostat_Main.resize(912, 665)
        self.centralwidget = QtWidgets.QWidget(Cryostat_Main)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setMouseTracking(False)
        self.mdiArea.setTabletTracking(False)
        self.mdiArea.setObjectName("mdiArea")
        self.PlottingWindow = QtWidgets.QWidget()
        self.PlottingWindow.setObjectName("PlottingWindow")
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        Cryostat_Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Cryostat_Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 912, 21))
        self.menubar.setObjectName("menubar")
        self.menuControl = QtWidgets.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuShow_Info_Dock = QtWidgets.QMenu(self.menuOptions)
        self.menuShow_Info_Dock.setObjectName("menuShow_Info_Dock")
        self.menuSystems_Online = QtWidgets.QMenu(self.menubar)
        self.menuSystems_Online.setObjectName("menuSystems_Online")
        self.menuOxford_Cryostat = QtWidgets.QMenu(self.menuSystems_Online)
        self.menuOxford_Cryostat.setObjectName("menuOxford_Cryostat")
        self.menuKeithley = QtWidgets.QMenu(self.menuSystems_Online)
        self.menuKeithley.setObjectName("menuKeithley")
        self.menuShow_Data = QtWidgets.QMenu(self.menubar)
        self.menuShow_Data.setObjectName("menuShow_Data")
        Cryostat_Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Cryostat_Main)
        self.statusbar.setObjectName("statusbar")
        Cryostat_Main.setStatusBar(self.statusbar)
        self.Main_dock_infobox = QtWidgets.QDockWidget(Cryostat_Main)
        self.Main_dock_infobox.setObjectName("Main_dock_infobox")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.MainDock_Seqstate = QtWidgets.QLabel(self.dockWidgetContents)
        self.MainDock_Seqstate.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainDock_Seqstate.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainDock_Seqstate.setAlignment(QtCore.Qt.AlignCenter)
        self.MainDock_Seqstate.setObjectName("MainDock_Seqstate")
        self.gridLayout_2.addWidget(self.MainDock_Seqstate, 2, 4, 1, 1)
        self.MainDock_Pressures = QtWidgets.QVBoxLayout()
        self.MainDock_Pressures.setObjectName("MainDock_Pressures")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.MainDock_Pressures.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainDock_HeLevel = QtWidgets.QProgressBar(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainDock_HeLevel.sizePolicy().hasHeightForWidth())
        self.MainDock_HeLevel.setSizePolicy(sizePolicy)
        self.MainDock_HeLevel.setMinimum(0)
        self.MainDock_HeLevel.setMaximum(100)
        self.MainDock_HeLevel.setProperty("value", 0)
        self.MainDock_HeLevel.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.MainDock_HeLevel.setObjectName("MainDock_HeLevel")
        self.horizontalLayout.addWidget(self.MainDock_HeLevel)
        self.MainDock_N2Level = QtWidgets.QProgressBar(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainDock_N2Level.sizePolicy().hasHeightForWidth())
        self.MainDock_N2Level.setSizePolicy(sizePolicy)
        self.MainDock_N2Level.setAccessibleDescription("")
        self.MainDock_N2Level.setInputMethodHints(QtCore.Qt.ImhNone)
        self.MainDock_N2Level.setMinimum(0)
        self.MainDock_N2Level.setMaximum(100)
        self.MainDock_N2Level.setProperty("value", 0)
        self.MainDock_N2Level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.MainDock_N2Level.setTextVisible(True)
        self.MainDock_N2Level.setInvertedAppearance(False)
        self.MainDock_N2Level.setObjectName("MainDock_N2Level")
        self.horizontalLayout.addWidget(self.MainDock_N2Level)
        self.MainDock_Pressures.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.MainDock_Pressures, 0, 7, 3, 1)
        self.MainDock_Seq2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.MainDock_Seq2.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainDock_Seq2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainDock_Seq2.setAlignment(QtCore.Qt.AlignCenter)
        self.MainDock_Seq2.setObjectName("MainDock_Seq2")
        self.gridLayout_2.addWidget(self.MainDock_Seq2, 1, 4, 1, 1)
        self.MainDock_Bset = QtWidgets.QLabel(self.dockWidgetContents)
        self.MainDock_Bset.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainDock_Bset.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainDock_Bset.setAlignment(QtCore.Qt.AlignCenter)
        self.MainDock_Bset.setObjectName("MainDock_Bset")
        self.gridLayout_2.addWidget(self.MainDock_Bset, 1, 2, 1, 1)
        self.MainDock_Trate = QtWidgets.QLabel(self.dockWidgetContents)
        self.MainDock_Trate.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainDock_Trate.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainDock_Trate.setAlignment(QtCore.Qt.AlignCenter)
        self.MainDock_Trate.setObjectName("MainDock_Trate")
        self.gridLayout_2.addWidget(self.MainDock_Trate, 2, 0, 1, 1)
        self.MainDock_Tnow = QtWidgets.QLabel(self.dockWidgetContents)
        self.MainDock_Tnow.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainDock_Tnow.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainDock_Tnow.setAlignment(QtCore.Qt.AlignCenter)
        self.MainDock_Tnow.setObjectName("MainDock_Tnow")
        self.gridLayout_2.addWidget(self.MainDock_Tnow, 0, 0, 1, 1)
        self.MainDock_Brate = QtWidgets.QLabel(self.dockWidgetContents)
        self.MainDock_Brate.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainDock_Brate.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainDock_Brate.setAlignment(QtCore.Qt.AlignCenter)
        self.MainDock_Brate.setObjectName("MainDock_Brate")
        self.gridLayout_2.addWidget(self.MainDock_Brate, 2, 2, 1, 1)
        self.MainDock_Tset = QtWidgets.QLabel(self.dockWidgetContents)
        self.MainDock_Tset.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainDock_Tset.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainDock_Tset.setAlignment(QtCore.Qt.AlignCenter)
        self.MainDock_Tset.setObjectName("MainDock_Tset")
        self.gridLayout_2.addWidget(self.MainDock_Tset, 1, 0, 1, 1)
        self.MainDock_Seqnow = QtWidgets.QLabel(self.dockWidgetContents)
        self.MainDock_Seqnow.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainDock_Seqnow.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainDock_Seqnow.setAlignment(QtCore.Qt.AlignCenter)
        self.MainDock_Seqnow.setObjectName("MainDock_Seqnow")
        self.gridLayout_2.addWidget(self.MainDock_Seqnow, 0, 4, 1, 1)
        self.MainDock_Bnow = QtWidgets.QLabel(self.dockWidgetContents)
        self.MainDock_Bnow.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainDock_Bnow.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainDock_Bnow.setAlignment(QtCore.Qt.AlignCenter)
        self.MainDock_Bnow.setObjectName("MainDock_Bnow")
        self.gridLayout_2.addWidget(self.MainDock_Bnow, 0, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 0, 1, 3, 1)
        self.line_8 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 0, 3, 3, 1)
        self.line_9 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 0, 5, 3, 1)
        self.Main_dock_infobox.setWidget(self.dockWidgetContents)
        Cryostat_Main.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.Main_dock_infobox)
        self.actionNew_Sequence = QtWidgets.QAction(Cryostat_Main)
        self.actionNew_Sequence.setObjectName("actionNew_Sequence")
        self.actionOpen = QtWidgets.QAction(Cryostat_Main)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(Cryostat_Main)
        self.actionSave_As.setObjectName("actionSave_As")
        self.action_show_Info_Dock = QtWidgets.QAction(Cryostat_Main)
        self.action_show_Info_Dock.setCheckable(True)
        self.action_show_Info_Dock.setObjectName("action_show_Info_Dock")
        self.action_show_Data = QtWidgets.QAction(Cryostat_Main)
        self.action_show_Data.setCheckable(True)
        self.action_show_Data.setObjectName("action_show_Data")
        self.action_run_LakeShore350 = QtWidgets.QAction(Cryostat_Main)
        self.action_run_LakeShore350.setCheckable(True)
        self.action_run_LakeShore350.setObjectName("action_run_LakeShore350")
        self.actionKeithley_Nanovolts = QtWidgets.QAction(Cryostat_Main)
        self.actionKeithley_Nanovolts.setCheckable(True)
        self.actionKeithley_Nanovolts.setObjectName("actionKeithley_Nanovolts")
        self.action_4 = QtWidgets.QAction(Cryostat_Main)
        self.action_4.setCheckable(True)
        self.action_4.setObjectName("action_4")
        self.action_show_ITC = QtWidgets.QAction(Cryostat_Main)
        self.action_show_ITC.setCheckable(True)
        self.action_show_ITC.setObjectName("action_show_ITC")
        self.action_run_ITC = QtWidgets.QAction(Cryostat_Main)
        self.action_run_ITC.setCheckable(True)
        self.action_run_ITC.setObjectName("action_run_ITC")
        self.action_run_ILM = QtWidgets.QAction(Cryostat_Main)
        self.action_run_ILM.setCheckable(True)
        self.action_run_ILM.setObjectName("action_run_ILM")
        self.action_run_IPS = QtWidgets.QAction(Cryostat_Main)
        self.action_run_IPS.setCheckable(True)
        self.action_run_IPS.setObjectName("action_run_IPS")
        self.action_run_Nanovolts = QtWidgets.QAction(Cryostat_Main)
        self.action_run_Nanovolts.setObjectName("action_run_Nanovolts")
        self.action_run_Current_sources = QtWidgets.QAction(Cryostat_Main)
        self.action_run_Current_sources.setObjectName("action_run_Current_sources")
        self.action_Logging = QtWidgets.QAction(Cryostat_Main)
        self.action_Logging.setCheckable(True)
        self.action_Logging.setObjectName("action_Logging")
        self.action_Logging_configuration = QtWidgets.QAction(Cryostat_Main)
        self.action_Logging_configuration.setCheckable(True)
        self.action_Logging_configuration.setObjectName("action_Logging_configuration")
        self.action_show_ILM = QtWidgets.QAction(Cryostat_Main)
        self.action_show_ILM.setCheckable(True)
        self.action_show_ILM.setObjectName("action_show_ILM")
        self.action_show_IPS = QtWidgets.QAction(Cryostat_Main)
        self.action_show_IPS.setCheckable(True)
        self.action_show_IPS.setObjectName("action_show_IPS")
        self.action_show_LakeShore350 = QtWidgets.QAction(Cryostat_Main)
        self.action_show_LakeShore350.setCheckable(True)
        self.action_show_LakeShore350.setObjectName("action_show_LakeShore350")
        self.action_show_Errors = QtWidgets.QAction(Cryostat_Main)
        self.action_show_Errors.setCheckable(True)
        self.action_show_Errors.setObjectName("action_show_Errors")
        self.action_plotLive = QtWidgets.QAction(Cryostat_Main)
        self.action_plotLive.setObjectName("action_plotLive")                      #######
        self.action_plotDatabase = QtWidgets.QAction(Cryostat_Main)
        self.action_plotDatabase.setObjectName("action_plotDatabase")
        self.actionLogging_LIVE = QtWidgets.QAction(Cryostat_Main)
        self.actionLogging_LIVE.setObjectName("actionLogging_LIVE")
        self.menuControl.addAction(self.actionNew_Sequence)
        self.menuControl.addAction(self.actionOpen)
        self.menuControl.addAction(self.actionSave_As)
        self.menuShow_Info_Dock.addAction(self.action_show_Info_Dock)
        self.menuShow_Info_Dock.addAction(self.action_show_Errors)
        self.menuShow_Info_Dock.addAction(self.action_show_Data)
        self.menuShow_Info_Dock.addSeparator()
        self.menuShow_Info_Dock.addAction(self.action_show_ITC)
        self.menuShow_Info_Dock.addAction(self.action_show_ILM)
        self.menuShow_Info_Dock.addAction(self.action_show_IPS)
        self.menuShow_Info_Dock.addSeparator()
        self.menuShow_Info_Dock.addAction(self.action_show_LakeShore350)
        self.menuOptions.addAction(self.menuShow_Info_Dock.menuAction())
        self.menuOptions.addAction(self.action_Logging_configuration)
        self.menuOxford_Cryostat.addAction(self.action_run_ITC)
        self.menuOxford_Cryostat.addAction(self.action_run_ILM)
        self.menuOxford_Cryostat.addAction(self.action_run_IPS)
        self.menuKeithley.addAction(self.action_run_Nanovolts)
        self.menuKeithley.addAction(self.action_run_Current_sources)
        self.menuSystems_Online.addAction(self.menuOxford_Cryostat.menuAction())
        self.menuSystems_Online.addSeparator()
        self.menuSystems_Online.addAction(self.action_run_LakeShore350)
        self.menuSystems_Online.addSeparator()
        self.menuSystems_Online.addAction(self.menuKeithley.menuAction())
        self.menuSystems_Online.addAction(self.action_Logging)
        self.menuSystems_Online.addAction(self.actionLogging_LIVE)
        self.menuShow_Data.addAction(self.action_plotLive)
        self.menuShow_Data.addAction(self.action_plotDatabase)
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuSystems_Online.menuAction())
        self.menubar.addAction(self.menuShow_Data.menuAction())

        self.retranslateUi(Cryostat_Main)
        self.menubar.triggered['QAction*'].connect(self.Main_dock_infobox.show)
        QtCore.QMetaObject.connectSlotsByName(Cryostat_Main)

    def valami(self):
            print("asdasd")


    def retranslateUi(self, Cryostat_Main):
        _translate = QtCore.QCoreApplication.translate
        Cryostat_Main.setWindowTitle(_translate("Cryostat_Main", "Cryostat GUI"))
        self.PlottingWindow.setWindowTitle(_translate("Cryostat_Main", "Subwindow"))
        self.PlottingWindow.setAccessibleName(_translate("Cryostat_Main", "Data"))
        self.menuControl.setTitle(_translate("Cryostat_Main", "Sequence"))
        self.menuOptions.setTitle(_translate("Cryostat_Main", "Options"))
        self.menuShow_Info_Dock.setTitle(_translate("Cryostat_Main", "Show"))
        self.menuSystems_Online.setTitle(_translate("Cryostat_Main", "Systems Online"))
        self.menuOxford_Cryostat.setTitle(_translate("Cryostat_Main", "Oxford Cryostat"))
        self.menuKeithley.setTitle(_translate("Cryostat_Main", "Keithley"))
        self.menuShow_Data.setTitle(_translate("Cryostat_Main", "Show Data"))
        self.MainDock_Seqstate.setText(_translate("Cryostat_Main", "Sequence state"))
        self.label.setText(_translate("Cryostat_Main", "He Level"))
        self.label_2.setText(_translate("Cryostat_Main", "N2 Level"))
        self.MainDock_HeLevel.setToolTip(_translate("Cryostat_Main", "He Level"))
        self.MainDock_HeLevel.setFormat(_translate("Cryostat_Main", "%p%"))
        self.MainDock_N2Level.setToolTip(_translate("Cryostat_Main", "N2 Level"))
        self.MainDock_N2Level.setFormat(_translate("Cryostat_Main", "%p%"))
        self.MainDock_Seq2.setText(_translate("Cryostat_Main", "Sequence misc"))
        self.MainDock_Bset.setText(_translate("Cryostat_Main", "Field set"))
        self.MainDock_Trate.setText(_translate("Cryostat_Main", "Temp rate"))
        self.MainDock_Tnow.setText(_translate("Cryostat_Main", "Temp now"))
        self.MainDock_Brate.setText(_translate("Cryostat_Main", "Field rate"))
        self.MainDock_Tset.setText(_translate("Cryostat_Main", "Temp set"))
        self.MainDock_Seqnow.setText(_translate("Cryostat_Main", "Sequence now"))
        self.MainDock_Bnow.setText(_translate("Cryostat_Main", "Field now"))
        self.actionNew_Sequence.setText(_translate("Cryostat_Main", "New Sequence"))
        self.actionOpen.setText(_translate("Cryostat_Main", "Open"))
        self.actionSave_As.setText(_translate("Cryostat_Main", "Save As"))
        self.action_show_Info_Dock.setText(_translate("Cryostat_Main", "Info Dock"))
        self.action_show_Data.setText(_translate("Cryostat_Main", "Data"))
        self.action_run_LakeShore350.setText(_translate("Cryostat_Main", "Lakeshore 350"))
        self.actionKeithley_Nanovolts.setText(_translate("Cryostat_Main", "Keithley Nanovolts"))
        self.action_4.setText(_translate("Cryostat_Main", "Keithley Current Source"))
        self.action_show_ITC.setText(_translate("Cryostat_Main", "ITC 503 "))
        self.action_run_ITC.setText(_translate("Cryostat_Main", "Temperature controller"))
        self.action_run_ILM.setText(_translate("Cryostat_Main", "Level Meter"))
        self.action_run_IPS.setText(_translate("Cryostat_Main", "Powersupply"))
        self.action_run_Nanovolts.setText(_translate("Cryostat_Main", "Nanovoltmeters"))
        self.action_run_Current_sources.setText(_translate("Cryostat_Main", "Current sources"))
        self.action_Logging.setText(_translate("Cryostat_Main", "Logging into database"))
        self.action_Logging_configuration.setText(_translate("Cryostat_Main", "Logging configuration"))
        self.action_show_ILM.setText(_translate("Cryostat_Main", "ILM 211"))
        self.action_show_IPS.setText(_translate("Cryostat_Main", "IPS 120"))
        self.action_show_LakeShore350.setText(_translate("Cryostat_Main", "Lakeshore 350"))
        self.action_show_Errors.setText(_translate("Cryostat_Main", "Errors"))
        self.action_plotLive.setText(_translate("Cryostat_Main", "Live"))
        self.action_plotDatabase.setText(_translate("Cryostat_Main", "Database"))
        self.actionLogging_LIVE.setText(_translate("Cryostat_Main", "Logging LIVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cryostat_Main = QtWidgets.QMainWindow()
    ui = Ui_Cryostat_Main()
    ui.setupUi(Cryostat_Main)
    Cryostat_Main.show()
    sys.exit(app.exec_())

