# -*- coding: utf-8 -*-
"""
Driver for the Keithley 2182 Nano-Voltmeter
"""

import threading, visa

import logging

# create a logger object for this module
logger = logging.getLogger(__name__)
# added so that log messages show up in Jupyter notebooks
logger.addHandler(logging.StreamHandler())

try:
    # the pyvisa manager we'll use to connect to the GPIB resources
    resource_manager = visa.ResourceManager('C:\\Windows\\System32\\agvisa32.dll')
except OSError:
    logger.exception("\n\tCould not find the VISA library. Is the National Instruments VISA driver installed?\n\n")


class Keithley2182(object):

    """
    The Keithley 2182 is a nano-voltmeter. You can find the full specifications
    list in the `user's guide`_.

    Example usage:

    >>> import instruments as ik
    >>> meter = ik.keithley.Keithley2182.open_gpibusb("/dev/ttyUSB0", 10)
    >>> print meter.measure(meter.Mode.voltage_dc)
    """
    def __init__(self, InstrumentAddress = None):



        self._visa_resource = resource_manager.open_resource(InstrumentAddress)
        # self._visa_resource.read_termination = '\r'
        self.CommunicationLock = threading.Lock()
        self.device = self._visa_resource


    def query(self, command):
        """Sends commands as strings to the device and receives strings from the device

        :param command: string generated by a given function, whom will be sent to the device
        :type command: str

        :return: answer from the device
        """
        with self.CommunicationLock:
            received = self.device.query(command)
        # self.CommunicationLock.release()
        return received.strip().split(',')

    def go(self, command):
        """Sends commands as strings to the device 

        :param command: string generated by a given function, whom will be sent to the device
        :type command: str

        """
        with self.CommunicationLock:
            self.device.write(command)




#    def measureTemperature(self):
#        self.sendcmd("SENS:CHAN 1")
#        self.sendcmd("SENS:FUNC 'TEMP'")
#        return self.query("SENS:DATA:FRES?")[0]

    def measureVoltage(self):
        """measure voltage
        :return: voltage in V
        :return type: float
        """


#        self.sendcmd("SENS:CHAN 1")
#        self.sendcmd("SENS:FUNC 'VOLT:DC'")
#        return self.query("SENS:DATA:FRES?")[0]
        return float(self.query(":READ?")[0])

    def DisplayOn(self):
        pass

    def DisplayOff(self):
        pass




